# Generated by Django 3.2.23 on 2024-01-26 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountnumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PossessionTitle',
            fields=[
                ('numberid', models.IntegerField(primary_key=True, serialize=False)),
                ('name_title', models.CharField(max_length=40)),
                ('color', models.CharField(blank=True, choices=[('1', 'button_preto'), ('2', 'button_vermelho'), ('3', 'button_azul'), ('4', 'button_amarelo'), ('5', 'button_verde'), ('6', 'button_verde1'), ('7', 'button_roxo'), ('8', 'button_laranja'), ('9', 'button_rosa')], max_length=1, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poss_account', to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dest_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_accounts', to='app.account')),
                ('update_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='TitleAttr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_attr', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_info', models.CharField(blank=True, choices=[('1', 'Casa'), ('2', 'Hotel')], max_length=1, null=True)),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_possession', to='app.possessiontitle')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPossession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_info', models.CharField(blank=True, choices=[('1', 'Casa'), ('2', 'Hotel')], max_length=1, null=True)),
                ('info_possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_infopossession', to='app.possessiontitle')),
            ],
        ),
    ]
