# Generated by Django 3.0.4 on 2020-03-30 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountnumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountnumbers', to='app.Account')),
            ],
        ),
    ]
